services:
  odoo:
    build: .
    ports:
      - "8069:8069"
      - "8072:8072"
    environment:
      - HOST=62.171.137.101
      - USER=odoo
      - PASSWORD=8EadLy4Eh7U6PJaZP04s1b
    volumes:
      - odoo-web-data:/var/lib/odoo
    restart: unless-stopped

volumes:
  odoo-web-data:
